### ISSUE TITLE
Missing page in Chinese version https://jenkins-x.io/zh/extending/

### ISSUE THREAD

**Issue by node** [jenkins-x/jenkins-x-website#11]
Need to translate pages under https://github.com/jenkins-x/jenkins-x-website/tree/master/extending .
@oleg-nenashev

**Comment by oleg-nenashev** [comment]
Hi. Thanks for the report, but what is the expectation from me here? I am neither Jenkins X Website maintainer nor Chinese speaker/translator.

**Comment by node** [comment]
Sorry for the mismatch AT :)   Actually I should AT @ZhaoXiaojie  here .

**Comment by LinuxSuRen** [comment]
You should report issues to https://github.com/jenkins-x/jx-docs. This repo is not the source repo.

**Comment by node** [comment]
Got it.
