### ISSUE TITLE
Dates on Articles Show Content From 2017

### ISSUE THREAD

**Issue by sherl0cks** [jenkins-x/jenkins-x-website#3]
I suspect that they should show 2018

https://github.com/jenkins-x/jenkins-x-website/blob/master/news/jep-400-submitted/index.html#L33
https://github.com/jenkins-x/jenkins-x-website/blob/master/news/introducing-jenkins-x/index.html#L31

![screenshot from 2018-03-19 18-03-08](https://user-images.githubusercontent.com/1335137/37624791-d1175e72-2b9f-11e8-8dd1-6163412c43b9.png)

**Comment by nashid** [comment]
The dates are shown correctly i.e. 2018, so this issue should be closed.

Check here: https://jenkins-x.io/news/

**Comment by pmuir** [comment]
Thanks!
