### ISSUE TITLE
Search/Indexing for http://jenkins-x.io/ is not for site

### ISSUE THREAD

**Issue by jrnt30** [jenkins-x/jenkins-x-website#5]
As a user, trying to search for content across the site, it looks like the "Search The Docs" has actually indexed the GoHugo content, not that of the Jenkins-X site. 

When attempting to search for something relevant (ex. `kubernetes`) there are no results returned.  Searching for something like (ex. `addons`) returns results not relevant to this project.

**Comment by michaelneale** [comment]
lets leave it int he jx repo (this is the generated website thing -not sure if shoud be tracking issues here as well?)
