### ISSUE TITLE
Problem displaying pages on http://jenkins-x.io/

### ISSUE THREAD

**Issue by mpailloncy** [jenkins-x/jenkins-x-website#6]
Seems like some static resources are missing (or an incorrect path is defined somewhere):

![image](https://user-images.githubusercontent.com/1479384/39516870-7fd8ac38-4dfe-11e8-9ccf-3ea28a36c2f0.png)

**Comment by mpailloncy** [comment]
I see that some pages or redirecting to https, is this a WIP maybe ?

**Comment by bwalding** [comment]
Looking into this now.

**Comment by bwalding** [comment]
Apex DNS is updated per Github docs - https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by mpailloncy** [comment]
Seems ok now, thx @bwalding
